// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewDeleter creates a new instance of Deleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Deleter {
	mock := &Deleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Deleter is an autogenerated mock type for the Deleter type
type Deleter struct {
	mock.Mock
}

type Deleter_Expecter struct {
	mock *mock.Mock
}

func (_m *Deleter) EXPECT() *Deleter_Expecter {
	return &Deleter_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type Deleter
func (_mock *Deleter) Delete(ctx context.Context, id string, password string) error {
	ret := _mock.Called(ctx, id, password)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Deleter_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Deleter_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - password string
func (_e *Deleter_Expecter) Delete(ctx interface{}, id interface{}, password interface{}) *Deleter_Delete_Call {
	return &Deleter_Delete_Call{Call: _e.mock.On("Delete", ctx, id, password)}
}

func (_c *Deleter_Delete_Call) Run(run func(ctx context.Context, id string, password string)) *Deleter_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Deleter_Delete_Call) Return(err error) *Deleter_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Deleter_Delete_Call) RunAndReturn(run func(ctx context.Context, id string, password string) error) *Deleter_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// NewUpdater creates a new instance of Updater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *Updater {
	mock := &Updater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Updater is an autogenerated mock type for the Updater type
type Updater struct {
	mock.Mock
}

type Updater_Expecter struct {
	mock *mock.Mock
}

func (_m *Updater) EXPECT() *Updater_Expecter {
	return &Updater_Expecter{mock: &_m.Mock}
}

// ChangeEmail provides a mock function for the type Updater
func (_mock *Updater) ChangeEmail(ctx context.Context, id string, newEmail string, password string) error {
	ret := _mock.Called(ctx, id, newEmail, password)

	if len(ret) == 0 {
		panic("no return value specified for ChangeEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, id, newEmail, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Updater_ChangeEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeEmail'
type Updater_ChangeEmail_Call struct {
	*mock.Call
}

// ChangeEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - newEmail string
//   - password string
func (_e *Updater_Expecter) ChangeEmail(ctx interface{}, id interface{}, newEmail interface{}, password interface{}) *Updater_ChangeEmail_Call {
	return &Updater_ChangeEmail_Call{Call: _e.mock.On("ChangeEmail", ctx, id, newEmail, password)}
}

func (_c *Updater_ChangeEmail_Call) Run(run func(ctx context.Context, id string, newEmail string, password string)) *Updater_ChangeEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Updater_ChangeEmail_Call) Return(err error) *Updater_ChangeEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Updater_ChangeEmail_Call) RunAndReturn(run func(ctx context.Context, id string, newEmail string, password string) error) *Updater_ChangeEmail_Call {
	_c.Call.Return(run)
	return _c
}

// ChangeUsername provides a mock function for the type Updater
func (_mock *Updater) ChangeUsername(ctx context.Context, id string, newUsername string, password string) error {
	ret := _mock.Called(ctx, id, newUsername, password)

	if len(ret) == 0 {
		panic("no return value specified for ChangeUsername")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, id, newUsername, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Updater_ChangeUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeUsername'
type Updater_ChangeUsername_Call struct {
	*mock.Call
}

// ChangeUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - newUsername string
//   - password string
func (_e *Updater_Expecter) ChangeUsername(ctx interface{}, id interface{}, newUsername interface{}, password interface{}) *Updater_ChangeUsername_Call {
	return &Updater_ChangeUsername_Call{Call: _e.mock.On("ChangeUsername", ctx, id, newUsername, password)}
}

func (_c *Updater_ChangeUsername_Call) Run(run func(ctx context.Context, id string, newUsername string, password string)) *Updater_ChangeUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Updater_ChangeUsername_Call) Return(err error) *Updater_ChangeUsername_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Updater_ChangeUsername_Call) RunAndReturn(run func(ctx context.Context, id string, newUsername string, password string) error) *Updater_ChangeUsername_Call {
	_c.Call.Return(run)
	return _c
}
