// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/cyberbrain-dev/taskery-api/internal/services"
	mock "github.com/stretchr/testify/mock"
)

// NewCreator creates a new instance of Creator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Creator {
	mock := &Creator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Creator is an autogenerated mock type for the Creator type
type Creator struct {
	mock.Mock
}

type Creator_Expecter struct {
	mock *mock.Mock
}

func (_m *Creator) EXPECT() *Creator_Expecter {
	return &Creator_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type Creator
func (_mock *Creator) Create(ctx context.Context, cmd services.CreateTaskCommand) error {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, services.CreateTaskCommand) error); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Creator_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Creator_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd services.CreateTaskCommand
func (_e *Creator_Expecter) Create(ctx interface{}, cmd interface{}) *Creator_Create_Call {
	return &Creator_Create_Call{Call: _e.mock.On("Create", ctx, cmd)}
}

func (_c *Creator_Create_Call) Run(run func(ctx context.Context, cmd services.CreateTaskCommand)) *Creator_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 services.CreateTaskCommand
		if args[1] != nil {
			arg1 = args[1].(services.CreateTaskCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Creator_Create_Call) Return(err error) *Creator_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Creator_Create_Call) RunAndReturn(run func(ctx context.Context, cmd services.CreateTaskCommand) error) *Creator_Create_Call {
	_c.Call.Return(run)
	return _c
}
