// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/cyberbrain-dev/taskery-api/internal/services"
	mock "github.com/stretchr/testify/mock"
)

// NewCompleter creates a new instance of Completer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Completer {
	mock := &Completer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Completer is an autogenerated mock type for the Completer type
type Completer struct {
	mock.Mock
}

type Completer_Expecter struct {
	mock *mock.Mock
}

func (_m *Completer) EXPECT() *Completer_Expecter {
	return &Completer_Expecter{mock: &_m.Mock}
}

// Complete provides a mock function for the type Completer
func (_mock *Completer) Complete(ctx context.Context, id string, ownerID string) error {
	ret := _mock.Called(ctx, id, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, ownerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Completer_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type Completer_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - ownerID string
func (_e *Completer_Expecter) Complete(ctx interface{}, id interface{}, ownerID interface{}) *Completer_Complete_Call {
	return &Completer_Complete_Call{Call: _e.mock.On("Complete", ctx, id, ownerID)}
}

func (_c *Completer_Complete_Call) Run(run func(ctx context.Context, id string, ownerID string)) *Completer_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Completer_Complete_Call) Return(err error) *Completer_Complete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Completer_Complete_Call) RunAndReturn(run func(ctx context.Context, id string, ownerID string) error) *Completer_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// NewCreator creates a new instance of Creator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Creator {
	mock := &Creator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Creator is an autogenerated mock type for the Creator type
type Creator struct {
	mock.Mock
}

type Creator_Expecter struct {
	mock *mock.Mock
}

func (_m *Creator) EXPECT() *Creator_Expecter {
	return &Creator_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type Creator
func (_mock *Creator) Create(ctx context.Context, cmd services.CreateTaskCommand) (string, error) {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, services.CreateTaskCommand) (string, error)); ok {
		return returnFunc(ctx, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, services.CreateTaskCommand) string); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, services.CreateTaskCommand) error); ok {
		r1 = returnFunc(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Creator_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Creator_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd services.CreateTaskCommand
func (_e *Creator_Expecter) Create(ctx interface{}, cmd interface{}) *Creator_Create_Call {
	return &Creator_Create_Call{Call: _e.mock.On("Create", ctx, cmd)}
}

func (_c *Creator_Create_Call) Run(run func(ctx context.Context, cmd services.CreateTaskCommand)) *Creator_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 services.CreateTaskCommand
		if args[1] != nil {
			arg1 = args[1].(services.CreateTaskCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Creator_Create_Call) Return(s string, err error) *Creator_Create_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Creator_Create_Call) RunAndReturn(run func(ctx context.Context, cmd services.CreateTaskCommand) (string, error)) *Creator_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewDeleter creates a new instance of Deleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Deleter {
	mock := &Deleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Deleter is an autogenerated mock type for the Deleter type
type Deleter struct {
	mock.Mock
}

type Deleter_Expecter struct {
	mock *mock.Mock
}

func (_m *Deleter) EXPECT() *Deleter_Expecter {
	return &Deleter_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type Deleter
func (_mock *Deleter) Delete(ctx context.Context, id string, ownerID string) error {
	ret := _mock.Called(ctx, id, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, ownerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Deleter_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Deleter_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - ownerID string
func (_e *Deleter_Expecter) Delete(ctx interface{}, id interface{}, ownerID interface{}) *Deleter_Delete_Call {
	return &Deleter_Delete_Call{Call: _e.mock.On("Delete", ctx, id, ownerID)}
}

func (_c *Deleter_Delete_Call) Run(run func(ctx context.Context, id string, ownerID string)) *Deleter_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Deleter_Delete_Call) Return(err error) *Deleter_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Deleter_Delete_Call) RunAndReturn(run func(ctx context.Context, id string, ownerID string) error) *Deleter_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// NewDeadlineRemover creates a new instance of DeadlineRemover. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeadlineRemover(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeadlineRemover {
	mock := &DeadlineRemover{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DeadlineRemover is an autogenerated mock type for the DeadlineRemover type
type DeadlineRemover struct {
	mock.Mock
}

type DeadlineRemover_Expecter struct {
	mock *mock.Mock
}

func (_m *DeadlineRemover) EXPECT() *DeadlineRemover_Expecter {
	return &DeadlineRemover_Expecter{mock: &_m.Mock}
}

// RemoveDeadline provides a mock function for the type DeadlineRemover
func (_mock *DeadlineRemover) RemoveDeadline(ctx context.Context, id string, ownerID string) error {
	ret := _mock.Called(ctx, id, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveDeadline")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, ownerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DeadlineRemover_RemoveDeadline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveDeadline'
type DeadlineRemover_RemoveDeadline_Call struct {
	*mock.Call
}

// RemoveDeadline is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - ownerID string
func (_e *DeadlineRemover_Expecter) RemoveDeadline(ctx interface{}, id interface{}, ownerID interface{}) *DeadlineRemover_RemoveDeadline_Call {
	return &DeadlineRemover_RemoveDeadline_Call{Call: _e.mock.On("RemoveDeadline", ctx, id, ownerID)}
}

func (_c *DeadlineRemover_RemoveDeadline_Call) Run(run func(ctx context.Context, id string, ownerID string)) *DeadlineRemover_RemoveDeadline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DeadlineRemover_RemoveDeadline_Call) Return(err error) *DeadlineRemover_RemoveDeadline_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DeadlineRemover_RemoveDeadline_Call) RunAndReturn(run func(ctx context.Context, id string, ownerID string) error) *DeadlineRemover_RemoveDeadline_Call {
	_c.Call.Return(run)
	return _c
}

// NewUpdater creates a new instance of Updater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *Updater {
	mock := &Updater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Updater is an autogenerated mock type for the Updater type
type Updater struct {
	mock.Mock
}

type Updater_Expecter struct {
	mock *mock.Mock
}

func (_m *Updater) EXPECT() *Updater_Expecter {
	return &Updater_Expecter{mock: &_m.Mock}
}

// Update provides a mock function for the type Updater
func (_mock *Updater) Update(ctx context.Context, id string, ownerID string, cmd services.UpdateTaskCommand) error {
	ret := _mock.Called(ctx, id, ownerID, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, services.UpdateTaskCommand) error); ok {
		r0 = returnFunc(ctx, id, ownerID, cmd)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Updater_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Updater_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - ownerID string
//   - cmd services.UpdateTaskCommand
func (_e *Updater_Expecter) Update(ctx interface{}, id interface{}, ownerID interface{}, cmd interface{}) *Updater_Update_Call {
	return &Updater_Update_Call{Call: _e.mock.On("Update", ctx, id, ownerID, cmd)}
}

func (_c *Updater_Update_Call) Run(run func(ctx context.Context, id string, ownerID string, cmd services.UpdateTaskCommand)) *Updater_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 services.UpdateTaskCommand
		if args[3] != nil {
			arg3 = args[3].(services.UpdateTaskCommand)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Updater_Update_Call) Return(err error) *Updater_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Updater_Update_Call) RunAndReturn(run func(ctx context.Context, id string, ownerID string, cmd services.UpdateTaskCommand) error) *Updater_Update_Call {
	_c.Call.Return(run)
	return _c
}
