// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/cyberbrain-dev/taskery-api/internal/domain/user/models"
	mock "github.com/stretchr/testify/mock"
)

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

type UserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepository) EXPECT() *UserRepository_Expecter {
	return &UserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type UserRepository
func (_mock *UserRepository) Create(u *models.User) error {
	ret := _mock.Called(u)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.User) error); ok {
		r0 = returnFunc(u)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - u *models.User
func (_e *UserRepository_Expecter) Create(u interface{}) *UserRepository_Create_Call {
	return &UserRepository_Create_Call{Call: _e.mock.On("Create", u)}
}

func (_c *UserRepository_Create_Call) Run(run func(u *models.User)) *UserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.User
		if args[0] != nil {
			arg0 = args[0].(*models.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserRepository_Create_Call) Return(err error) *UserRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepository_Create_Call) RunAndReturn(run func(u *models.User) error) *UserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type UserRepository
func (_mock *UserRepository) Delete(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type UserRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id string
func (_e *UserRepository_Expecter) Delete(id interface{}) *UserRepository_Delete_Call {
	return &UserRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *UserRepository_Delete_Call) Run(run func(id string)) *UserRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserRepository_Delete_Call) Return(err error) *UserRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepository_Delete_Call) RunAndReturn(run func(id string) error) *UserRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type UserRepository
func (_mock *UserRepository) FindByEmail(email string) (*models.User, error) {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*models.User, error)); ok {
		return returnFunc(email)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *models.User); ok {
		r0 = returnFunc(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type UserRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - email string
func (_e *UserRepository_Expecter) FindByEmail(email interface{}) *UserRepository_FindByEmail_Call {
	return &UserRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", email)}
}

func (_c *UserRepository_FindByEmail_Call) Run(run func(email string)) *UserRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserRepository_FindByEmail_Call) Return(user *models.User, err error) *UserRepository_FindByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserRepository_FindByEmail_Call) RunAndReturn(run func(email string) (*models.User, error)) *UserRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type UserRepository
func (_mock *UserRepository) FindByID(id string) (*models.User, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*models.User, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *models.User); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type UserRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id string
func (_e *UserRepository_Expecter) FindByID(id interface{}) *UserRepository_FindByID_Call {
	return &UserRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *UserRepository_FindByID_Call) Run(run func(id string)) *UserRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserRepository_FindByID_Call) Return(user *models.User, err error) *UserRepository_FindByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserRepository_FindByID_Call) RunAndReturn(run func(id string) (*models.User, error)) *UserRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type UserRepository
func (_mock *UserRepository) Update(u *models.User) error {
	ret := _mock.Called(u)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.User) error); ok {
		r0 = returnFunc(u)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type UserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - u *models.User
func (_e *UserRepository_Expecter) Update(u interface{}) *UserRepository_Update_Call {
	return &UserRepository_Update_Call{Call: _e.mock.On("Update", u)}
}

func (_c *UserRepository_Update_Call) Run(run func(u *models.User)) *UserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.User
		if args[0] != nil {
			arg0 = args[0].(*models.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserRepository_Update_Call) Return(err error) *UserRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepository_Update_Call) RunAndReturn(run func(u *models.User) error) *UserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenProvider creates a new instance of TokenProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenProvider {
	mock := &TokenProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenProvider is an autogenerated mock type for the TokenProvider type
type TokenProvider struct {
	mock.Mock
}

type TokenProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenProvider) EXPECT() *TokenProvider_Expecter {
	return &TokenProvider_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type TokenProvider
func (_mock *TokenProvider) Generate(userID string) (string, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenProvider_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type TokenProvider_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - userID string
func (_e *TokenProvider_Expecter) Generate(userID interface{}) *TokenProvider_Generate_Call {
	return &TokenProvider_Generate_Call{Call: _e.mock.On("Generate", userID)}
}

func (_c *TokenProvider_Generate_Call) Run(run func(userID string)) *TokenProvider_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TokenProvider_Generate_Call) Return(s string, err error) *TokenProvider_Generate_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *TokenProvider_Generate_Call) RunAndReturn(run func(userID string) (string, error)) *TokenProvider_Generate_Call {
	_c.Call.Return(run)
	return _c
}
