// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewAuthenticator creates a new instance of Authenticator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthenticator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Authenticator {
	mock := &Authenticator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Authenticator is an autogenerated mock type for the Authenticator type
type Authenticator struct {
	mock.Mock
}

type Authenticator_Expecter struct {
	mock *mock.Mock
}

func (_m *Authenticator) EXPECT() *Authenticator_Expecter {
	return &Authenticator_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type Authenticator
func (_mock *Authenticator) Login(ctx context.Context, email string, password string) (string, error) {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Authenticator_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type Authenticator_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *Authenticator_Expecter) Login(ctx interface{}, email interface{}, password interface{}) *Authenticator_Login_Call {
	return &Authenticator_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *Authenticator_Login_Call) Run(run func(ctx context.Context, email string, password string)) *Authenticator_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Authenticator_Login_Call) Return(s string, err error) *Authenticator_Login_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Authenticator_Login_Call) RunAndReturn(run func(ctx context.Context, email string, password string) (string, error)) *Authenticator_Login_Call {
	_c.Call.Return(run)
	return _c
}

// NewRegistrar creates a new instance of Registrar. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegistrar(t interface {
	mock.TestingT
	Cleanup(func())
}) *Registrar {
	mock := &Registrar{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Registrar is an autogenerated mock type for the Registrar type
type Registrar struct {
	mock.Mock
}

type Registrar_Expecter struct {
	mock *mock.Mock
}

func (_m *Registrar) EXPECT() *Registrar_Expecter {
	return &Registrar_Expecter{mock: &_m.Mock}
}

// Register provides a mock function for the type Registrar
func (_mock *Registrar) Register(ctx context.Context, username string, email string, password string) error {
	ret := _mock.Called(ctx, username, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, username, email, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Registrar_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type Registrar_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - email string
//   - password string
func (_e *Registrar_Expecter) Register(ctx interface{}, username interface{}, email interface{}, password interface{}) *Registrar_Register_Call {
	return &Registrar_Register_Call{Call: _e.mock.On("Register", ctx, username, email, password)}
}

func (_c *Registrar_Register_Call) Run(run func(ctx context.Context, username string, email string, password string)) *Registrar_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Registrar_Register_Call) Return(err error) *Registrar_Register_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Registrar_Register_Call) RunAndReturn(run func(ctx context.Context, username string, email string, password string) error) *Registrar_Register_Call {
	_c.Call.Return(run)
	return _c
}
